version: '3.8'

services:
  postgres:
    image: postgres:13.2
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dwh-api-v3
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/development/postgres/pgdata:/var/lib/postgresql/data/pgdata
  postgres_test:
    image: postgres:13.2
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tmr_test

